- name: install haproxy on the load balance VM
  dnf:
   name: haproxy
   state: latest
  when: ansible_distribution == "CentOS"

- name: start and enable haproxy
  service:
   name: haproxy
   state: started
   enabled: yes

- name: generate the HAproxy configuration
  vars:
   server_list:
    - name: websrv1
      ip: 192.168.1.214
      port: 80
    - name: websrv2
      ip: 192.168.1.176
      port: 80
  template:
   src: haproxy.cfg.j2
   dest: /etc/haproxy/haproxy.cfg
   owner: root
   group: root
   mode: 0644
