- name: install haproxy on the load balance VM
  dnf:
   name: haproxy
   state: latest
  when: ansible_distribution == "CentOS"

- name: start and enable haproxy
  service:
   name: haproxy
   state: started
   enabled: yes

- name: generate the HAproxy configuration
  template:
   src: haproxy.cfg.j2
   dest: /etc/haproxy/haproxy.cfg
   owner: root
   group: root
   mode: 0644

- name: install keepalived on the proxy servers
  dnf:
   name: keepalived
   state: latest
  when: ansible_distribution == "CentOS"
 
- name: generate keepalived conf
  template:
   src: keepalived.conf.j2
   dest: /etc/keepalived/keepalived.conf
   owner: root
   group: root
   mode: 0644  

- name: enable and start keepalived service
  service:
   name: keepalived
   state: started
   enabled: yes
