---

    #Updating CentOS

- hosts: all
  become: true
  pre_tasks:

  - name: install updates CentOS
    tags: always
    dnf: 
     update_only: yes
     update_cache: yes
    when: ansible_distribution == "CentOS"

     # ROLES

- hosts: all
  become: true
  roles: 
   - base

- hosts: workstations
  become: true
  roles:
   - workstations

- hosts: webservers
  become: true
  roles:
   - webservers

- hosts: proxyserver
  become: true
  roles:
   - proxyserver

- hosts: proxyserver
  become: true
  roles:
   - keepalived
