- name: install nginx for CentOS
  dnf:
   name: nginx
   state: latest
  when: ansible_distribution == "CentOS"
    
- name: start and enable nginx
  service:
   name: nginx
   state: started
   enabled: yes
  when: ansible_distribution == "CentOS"

- name: push the index.html file for our nginx backends
  template:
   src: index.html.j2
   dest: /usr/share/nginx/html/index.html
   owner: root
   group: root
   mode: 0644

- name: make sure firewalld service is running
  service:
   name: firewalld
   state: started

- name: open port 80 in firewalld
  firewalld:
   service: http
   permanent: yes
   state: enabled
