- name: install nginx for CentOS
  dnf:
   name: nginx
   state: latest
  when: ansible_distribution == "CentOS"
    
- name: start and enable nginx
  service:
   name: nginx
   state: started
   enabled: yes
  when: ansible_distribution == "CentOS"

- name: copy index.html file for our nginx backend A
  copy:
   src: nginxservera.html
   dest: /usr/share/nginx/html/index.html
   owner: root
   group: root
   mode: 0644
  when: ansible_hostname == "websrv1" 

- name: copy index.html file for our nginx backend B
  copy:
   src: nginxserverb.html
   dest: /usr/share/nginx/html/index.html
   owner: root
   group: root
   mode: 0644
  when:  ansible_hostname == "websrv2"

- name: make sure firewalld service is running
  service:
   name: firewalld
   state: started

- name: open port 80 in firewalld
  firewalld:
   service: http
   permanent: yes
   state: enabled
